### PR TITLE
Change dashes to N/A

### PR DESCRIPTION
**Pull request by buckley-w-david**
This PR changes the display for not applicable fields from `--` to `N/A` (and equivalent French)

### CODE REVIEW

**Comment by konklone** [comment]
I fully agree that `--` isn't explanatory (and I've paid the penalty for this by explaining it directly to agencies over email several times now!), but is N/A accurate? 

Unless there are other changes I missed, it's describing ephemeral connection failures, not eligibility. An `N/A` implies that the service isn't eligible to be scanned for that or in scope for evaluation. I worry that though it may raise less questions, it also might give the wrong impression.

**Comment by buckley-w-david** [comment]
You have a point, but unless I am misunderstanding something it's not just describing ephemeral failures. 

for example if a site does not support https at all, the various specific measurements taken of things like their signature algorithm, or attributes of their certificate cannot even be measured, so would not really be pass or fail, but some kind of null value, which is being represented as N/A.

That being said, now that you raise the issue I agree that it is worrisome.

@sidewalkballet what do you think?

**Comment by sidewalkballet** [comment]
Yes, we could have something a bit less dismiss-able (people could see N/A and think they don't need to worry about it, when they actually do). We do have a definition of why the value would be N/A on the app but I'm open to suggestions for something that can be both readable and actionable. I'm mulling it over 🤔

**Comment by konklone** [comment]
It should be possible to separate the two cases - maybe longer text is worthwhile?

* If HTTPS is not supported: "HTTPS not supported"
* If HTTPS is supported but connectivity failed: "Scanner couldn't connect"

Just some first attempts...

**Pull request merged**
