### PR TITLE
Handle request error

### PR DESCRIPTION
**Pull request by timarney**
Handles error as noted in https://github.com/cds-snc/track-web/issues/105.

Do we want to show something in the UI that the error happened?  Seems like maybe it's okay without as the next page says "no data available" and I don't see anything on the front page that "looks" broken.  That said I haven't seen the working version :) 

screen shot 2019-01-02 at 1 56 56 pm

### CODE REVIEW

**Comment by timarney** [comment]
Made a further update to hide the "Domains that enforce HTTPS" text on the homepage unless the request for data was successful.

screen shot 2019-01-03 at 8 31 48 am

**Comment by obrien-j** [comment]
Looks good @timarney ... Any ideas for equivalent handling of the domains/orgs page....

On those, it might be worthwhile throwing up a more visible error to the user, otherwise, it's going to just look bizarre.

Might as well merge this while @sayaHub or you thinks about the next portion.

**Comment by obrien-j** [comment]
Ahh. Gold.

Might pick your brain next week on how to setup a similar staging view
deployment to ircc/vac for PR based views... Not very optimized right now.

**Comment by timarney** [comment]
For tracking purposes here's the other page showing the no data available message.

screen shot 2019-01-07 at 9 30 18 am

**Pull request merged**
